### ISSUE TITLE
On the creation of a comprehensive testing framework.

### ISSUE THREAD

**Issue by naripok** [AirGrid/edgekit#131]
# Summary

This issue will outline a proposal for the creation of a comprehensive testing framework.

Here will discuss the ideas behind the testing suite, its structure, coverage goals and technologies.

The main goal is to create a healthy environment, favouring development efficiency and velocity while maintaining robustness, simplicity and reduced onboarding effort.

## Ideological basis
Ideally, a test suite should outline the desired behaviour of a program. Think of documentation that can be executed.
It should be legible, significative, and it should cover the broader input/output space as possible.

Some guidelines can be used to assure such qualities:
- Write tests for behaviours, not for implementation details;
  - it should read as documentation and be clear about what is the expected behaviour it tests for;
  - a test suite should be useful while developing new features, as well as while refactoring and optimizing existing ones;
  - it should not break nor require changes while the behaviours it describes remain unchanged;
- Use tests as an aid for thinking;
  - writing tests along with implementation helps to outline the desired behaviour of a program while assuring its subjects are well divided and easily testable;
  - writing tests before implementation and seeing it fails helps to keep false negative counts as low as possible;
- Generate your tests when you can;
  - generative testing helps to give you confidence that the implementation follows the expected behaviour for a broad input/output space;
  - it helps the developers, finding unthought edge-cases;
- Test as many paths as possible;
  - the unit test suite should be complete, with a unit test for each exposed API at least;
  - the end-to-end test suite should cover at least the 'happy paths' of the application, using mocks to simulate the error scenarios while maintaining execution time low;
- Maintain test execution time low;
  - if the test suite becomes a burden on development, if it breaks the state of flow, developers will not use it;
  - ideally, a test unit test suite should take no more than 4-5 seconds to run, and it should run every time a file is saved;
  - for end-to-end tests, the time requirements are less restricted as it will run less often;

## Structure
Ideally, the test suite structure should be unambiguous and consistent.

In my view, things should be aggregated on a module basis.
Each module would be its own test suite, while fixtures, generators and helper methods would be extracted for reuse.
Something like the following (this is just an example):
```
src
|-main
|  |-index.ts
|  |-moduleFuncs.ts
|  |-moreFuncs.ts
|-someModule
|  |-index.ts
|-utils
   |-index.ts

test
|-fixtures
|  |-someMock.json
|  |-someOther.json
|-helpers
|  |-generators
|  |  |-domain.ts
|  |  |-application.ts
|  |-utils
|  |  |-setupNCleaning.ts
|  |  |-mockFactories.ts
|-unit
|  |-main
|  |  |-index.test.ts
|  |  |-moduleFuncs.test.ts
|  |  |-moreFuncs.test.ts
|  |-someModule
|  |  |-index.test.ts
|  |-utils
|    |-index.test.ts
|-e2e
   |-main
   |  |-index.test.ts
   |-someModule
   |  |-index.test.ts 
   |-snapshots
   |  |-snap.json
.
.
.

```

Inside each testing module, suites should be organized at the function/class level.
They should be written in a descriptive/declarative manner, specifying the desired behaviour for testing.
Ideally, the code should explain itself. If there is a need for too many comments, the test item probably can be divided into more than one, more descriptive items.

Something like:
```typescript
describe('methodOne surface behaviour', () => {
  beforeAll(() => {
    setup()
  })
  afterAll(() => {
    teardown()
  })
  it('should not throw errors for valid inputs', () => {
    method.call(validInput)
  })
  it('should throw on invalid inputs', () => {
    expect(() => {
      method.call(invalidInput)
    }).toThrow(/invalid input/)
  })
  it('should return valid objects', () => {
    const rep = method.call(validInput)
    expect(rep).toEqual(expectedRep)
  })
})

describe('methodTwo surface behaviour', () => {
  ...
})
```

## Coverage
As uncle Bob Martin would [say (demand)](https://twitter.com/unclebobmartin/status/55954057327677440):

> Every single line of code that you write should be tested

While not every target can always be achieved, we should still have a target to aim for. Mainly the implementation should be done (when possible) in a way that each method is easily testable, meaning: [deterministic](https://en.wikipedia.org/wiki/Deterministic_algorithm) and [pure](https://en.wikipedia.org/wiki/Pure_function). There also must be [minimal branching as possible](https://en.wikipedia.org/wiki/Cyclomatic_complexity).

## Roadmap
I suggest we proceed as follows (in order of importance):
- [x] organize the suite structure
- [x] clean current unit tests, extracting shared helpers, mocks and fixtures
- [x] write/improve tests targeting missing execution environments
- [ ] substitute end-to-end testing framework
- [ ] create a strategy for improving test coverage

### Progress
[Organize the suite structure](https://github.com/AirGrid/edgekit/pull/132)

# Related
POCs and related stuff:
- [Wrapper testing issue](https://github.com/AirGrid/rmap/issues/397)
- [Fast-check POC](https://github.com/AirGrid/edgekit/issues/108)
- [Cypress POC](https://github.com/AirGrid/edgekit-platform/pull/326)
- [Playwright POC](https://github.com/AirGrid/edgekit-platform/pull/330)

Issues with the current testing setup
- [Edkt library modules](https://github.com/AirGrid/edgekit/issues/104)
- [Remove jest-puppetter](https://github.com/AirGrid/rmap/issues/383)
- [Remove mocks for edkt library](https://github.com/AirGrid/rmap/issues/344)
- [Testing on production tables](https://github.com/AirGrid/rmap/issues/366)
